version: '3'

services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=537865
      - PGDATA=/var/lib/postgresql/data/pgdata
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - pg_data:/var/lib/postgresql/data/pgdata
    ports:
      - '5432:5432'

  app:
    build: .
    tty: true
    command: python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8000
    ports:
      - '8000:8000'
    depends_on:
      db:
        condition: service_healthy

  celery:
    build: .
    command: celery -A config worker -l INFO && celery -A config beat -l INFO -S django
    depends_on:
      - redis
      - app

volumes:
  pg_data:
