version: '3'

services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=537865
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - pg_data:/var/lib/postgresql/data/pgdata
    ports:
      - '15432:15432'
    healthcheck:
      test: ['CMD-SHELL', 'pg-isready']
      interval: 10s
      timeout: 10s
      retries: 5

  app:
    build: .
    tty: true
    command: python3 manage.py runserver 0.0.0.0:8000
    ports:
      - '8001:8000'
    depends_on:
      db:
        condition: service_healthy

  celery:
    build: .
    command: celery -A config beat -l INFO -S django
    depends_on:
      - redis
      - app

volumes:
  pg_data: